name: Update token list

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch: {}

jobs:
  sync:
    runs-on: ubuntu-latest
    name: Sync

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Yarn Cache
        uses: actions/cache@v2
        with:
          path: ./.yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - run: yarn build-token-list
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.DIST_DEPLOY_KEY }}
          publish_dir: ./data
          publish_branch: master
          external_repository: saber-hq/saber-lp-token-list
